import random

puzzles = [
    "Nurikabe", "Unique Nurikabe", "Torch", "Lakes", "Box", "Creek",
    "Mochikoro", "Tasquare", "Kurotto", "Nuribou", "Tawamurenga", "Look-Air",
    "Mochinyoro", "Tapa", "Echo", "Cave", "Nurimisaki", "Snake", "Nonogram",
    "International Borders", "Aqre", "Chained Block", "Canal View", "Choco Banana",
    "Coral", "Nuri-uzu", "Ququ", "Cross the Streams", "Dominion", "Light and Shadow",
    "Norinuri", "Circles and Squares", "Tetro Chain-Y", "Mirroring Tile",
    "Battenberg Painting", "Snake Egg", "Archipelago", "Nibun-nogo", "Inaba's Island",
    "Isowatari", "City Space", "Sashikabe", "Tetro Chain-K", "Sansa Road",
    "Tilepaint", "Norinori", "Nuri-Maze", "LITS", "Inverse LITSO", "Shimaguni",
    "Stostone", "Paintarea", "Chocona", "Aquarium", "Parquet", "Hinge", "Heyablock",
    "Cocktail Lamp", "Kuroclone", "Martini", "Patchwork", "Mannequin Gate",
    "Kuromenbun", "Tile City", "Nuritwin", "Heyawake", "Hitori", "Kurodoko",
    "Uso-one", "Yajisan-Kazusan", "Kurochute", "Ayeheya", "One Room One Door",
    "No Three", "Context", "Akichiwake", "Guide Arrow", "Aquapelago", "Territory",
    "Curving Road", "Smullyanic Dynasty", "Out Of Sight", "Sumiwake", "Slitherlink",
    "Vertex Slitherlink", "Touch Slitherlink", "Wolves and Sheep Fences", "Masyu",
    "Hexagonal Masyu", "Yajilin", "Slalom", "Nagareru-Loop", "Moon or Sun",
    "Country Road", "Onsen-meguri", "Mejilink", "Angle Loop", "Double Back", "Scrin",
    "Regional Yajilin", "Geradeweg", "Castle Wall", "Maxi Loop", "Mid-loop",
    "Balance Loop", "Imbalance Loop", "Simple Loop", "Detour", "Haisu",
    "Tapa-Like Loop", "Dotchi-Loop", "Ovotovata", "Building Walk", "Rail Pool",
    "Disorderly Loop", "Ant Mill", "Koburin", "Remembered Length", "Nanameguri",
    "Myopia", "Water Walk", "Kaisu", "Mukkonn Enn", "All or Nothing",
    "Line of Sight", "Persistence of Memory", "LIX Loop", "Portal Loop",
    "Bosnian Road", "Fire Walk", "Fake Arrow", "Turnaround", "Dotchi Dotchi Loop",
    "Retsurin", "Kurarin", "Bunnyhop", "Morning Walk", "Reflect Link", "Pipelink",
    "Loop Special", "Nagenawa", "Kouchoku", "Ring-ring", "Crossstitch",
    "Round Trip", "Train Stations", "Turn and Run", "Orbital", "Icebarn",
    "Pipelink Returns", "Barns", "Icelom", "Icelom 2", "Ice Walk", "Numberlink",
    "Shirokuro-link", "Kusabi", "Arukone", "Rassi Silai", "Anglers", "Mintonette",
    "Wataridori", "U-Turns", "Hashiwokakero", "Hashi Tree", "Hotaru Beam",
    "Ichimaga", "Magnetic Ichimaga", "Crossing Ichimaga", "Amibo", "Coffee Milk",
    "Ladders", "Heyapin", "Forest Walk", "Diamond Chain", "Energy Walk", "Herugolf",
    "Return Home", "Yosenabe", "Army Ants", "Bonsan", "Heya-Bon",
    "Rectangle-Slider", "Satogaeri", "Yajisan-Sokoban", "Oyakodori", "Brownies",
    "Time Bomb", "Blind Rush", "Shikaku", "Domino Search", "Gravel", "Border Block",
    "FiveCells", "Sashigane", "Nawabari", "Tri-place", "FourCells",
    "Aho-ni-Narikire", "Heteromino", "Double Choco", "Triangular Double Choco",
    "Compass", "Araf", "NIKOJI", "Lohkous", "La Paz", "Pentominous", "Tetrominous",
    "Tonttiraja", "Taj Mahal", "Mirror Block", "Family Photo", "Slash Pack",
    "Fractional Division", "Sashikazune", "Tachiawase Block", "Subomino",
    "Meidjuluk", "Balloon Box", "Narrowfence", "Tentaisho", "KaitoRamma",
    "New KaitoRamma", "Goats and Wolves", "Combi Block", "L-route", "Voxas",
    "Tatamibari", "Fillmat", "Uso-tatami", "Yajitatami", "Square Jam", "Kakuro",
    "Even Loop Kakuro", "Shape Minesweeper", "Minarism", "Sukoro", "Neighbors",
    "Sky Neighbors", "Kakuru", "View", "Bosanowa", "Skyscrapers", "Kropki",
    "Easy as ABC", "ABC-Box", "Magic Snail", "Magic Summer", "Doppelblock",
    "Number Rope", "Simple Gako", "Japanese Sums", "Japanese Sums with Zeroes",
    "Japanese Arrows", "Consecutive Kakuro", "Slovak Sums", "Sudoku", "Fillomino",
    "Snaky Fillomino", "Symmetry Area", "Ripple Effect", "Rooms of Factors",
    "Makaro", "Nanro", "Cojun", "Renban-Madoguchi", "Sukoro-room", "Hanare-gumi",
    "Kazunori Room", "Meandering Numbers", "Putteria", "Toichika 2", "Snake Pit",
    "Wafusuma", "San-Anko", "Twin Area", "Number City", "Juosan", "Slant",
    "Tatebo-Yokobo", "Wagiri", "Wall Logic", "Four Winds", "Four Winds with Parks",
    "Wind Kabe", "Curve Data", "Litherslink", "Recoil", "T-Junction", "Akari",
    "Regional Akari", "Goishi", "Shakashaka", "Kin-Kon-Kan", "Hebi-Ichigo",
    "School Trip", "Pencils", "Tents", "Minesweeper", "Tren", "Stairwell",
    "Takoyaki", "Magnets", "Battleships", "Place by Product",
    "Wittgenstein Briquet", "Zabajaba", "Yajirushi 2", "Arrow Flow", "Distopia",
    "Dosun-Fuwari", "Hakoiri-masashi", "Roma", "Toichika", "Nondango", "Yin-Yang",
    "Yin-Yang Mines", "Star Battle", "Star Gazing", "Statue Park", "Pentopia",
    "Lollipops", "NEWS", "Evolmino", "Tontonbeya", "Penta Touch", "Alternation",
    "Kissing Polyominoes", "Retrograde Battleships", "Regional Polyominoes",
    "Yajirushi"
]

print("随机谜题:", random.choice(puzzles))